const $ = (s, root = document) => root.querySelector(s);
const app = $('#app');
const today = () => new Date().toISOString().slice(0, 10);
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
const money = (n) => `${new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(n)} ₽`;
const chartMoney = (n) => n === 0 ? '0 ₽' : n < 1000 ? money(n) : `${new Intl.NumberFormat('ru-RU', { maximumFractionDigits: n < 100000 ? 1 : 0 }).format(n / 1000)} тыс. ₽`;
const dateText = (iso) => new Intl.DateTimeFormat('ru-RU').format(new Date(`${iso}T12:00:00`));
const monthText = (key) => new Intl.DateTimeFormat('ru-RU', { month: 'long', year: 'numeric' }).format(new Date(`${key}-01T12:00:00`)).replace(/^./, (x) => x.toUpperCase());
const monthKey = (date) => date.slice(0, 7);
const defaultCategories = [['Супермаркеты','bag'],['Транспорт','bus'],['Жильё','home'],['Здоровье','health'],['Развлечения','play'],['Одежда','shirt'],['Путешествия','plane'],['Другое','dots']];
const iconLabel = {bag:'Корзина',car:'Автомобиль',bus:'Автобус',home:'Дом',health:'Сердце',cross:'Аптечный крест',dumbbell:'Гантель',book:'Книга',cup:'Чашка',cutlery:'Ресторан',gift:'Подарок',film:'Кино',music:'Музыка',game:'Игра',pet:'Домашнее животное',baby:'Ребёнок',education:'Образование',work:'Работа',phone:'Телефон',wifi:'Интернет',subscription:'Подписка',card:'Банковская карта',tools:'Инструменты',repair:'Ремонт',beauty:'Красота',flower:'Цветок',camera:'Фотоаппарат',bike:'Велосипед',fuel:'Топливо',shirt:'Одежда',plane:'Самолёт',train:'Поезд',umbrella:'Зонтик',dots:'Другое'};
const icon = (name) => ({
  bag:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8h16l-1 12H5L4 8Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></svg>',
  bus:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="3" width="14" height="15" rx="3"/><path d="M5 9h14M8 21l1-3m6 3-1-3M8 13h2m4 0h2"/></svg>',
  home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1V10Z"/></svg>',
  health:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 8.5c0 5.3-8.8 10.2-8.8 10.2S3.2 13.8 3.2 8.5A4.8 4.8 0 0 1 12 5.8a4.8 4.8 0 0 1 8.8 2.7Z"/></svg>',
  play:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 5 11 7-11 7V5Z"/></svg>',
  car:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16 1.5-6h13l1.5 6v4H4zM7 10l1.5-3h7l1.5 3M7 18h.01m10 0h.01"/></svg>',
  cross:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6z"/></svg>',
  dumbbell:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9v6m3-8v10m3-5h4m3-5v10m3-8v6"/></svg>',
  book:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4.5A3.5 3.5 0 0 1 7.5 1H20v18H7.5A3.5 3.5 0 0 0 4 22.5zM4 4.5V20"/></svg>',
  cup:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h12v8a6 6 0 0 1-12 0zM17 7h2a2 2 0 0 1 0 4h-2M4 22h14"/></svg>',
  cutlery:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3v8m-3-8v5a3 3 0 0 0 6 0V3m-3 8v10M18 3v18m0-18c3 2 3 7 0 8"/></svg>',
  gift:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9h18v12H3zM12 9v12M2 5h20v4H2zM12 5H8a2 2 0 1 1 2-2c0 2-2 2-2 2m4 0h4a2 2 0 1 0-2-2c0 2 2 2 2 2"/></svg>',
  film:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 4v16m10-16v16M3 9h4m10 0h4m-18 6h4m10 0h4"/></svg>',
  music:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V5l10-2v13M9 18a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm10-2a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Z"/></svg>',
  game:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 8h10a4 4 0 0 1 3.8 5.2l-1.1 3.5a2 2 0 0 1-3.3.8l-1.6-1.5h-5.6l-1.6 1.5a2 2 0 0 1-3.3-.8l-1.1-3.5A4 4 0 0 1 7 8Z"/><path d="M7 12v4m-2-2h4m8-2h.01m2 2h.01"/></svg>',
  pet:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="8" r="2"/><circle cx="18" cy="8" r="2"/><circle cx="9" cy="4" r="2"/><circle cx="15" cy="4" r="2"/><path d="M12 11c-3.5 0-6 2.5-6 5a3 3 0 0 0 6 1.5A3 3 0 0 0 18 16c0-2.5-2.5-5-6-5Z"/></svg>',
  baby:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"/><path d="M6 21v-2a6 6 0 0 1 12 0v2M9 7h.01m6 0h.01M10 10c1 .8 3 .8 4 0"/></svg>',
  education:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m2 9 10-5 10 5-10 5zM6 11v5c3 2 9 2 12 0v-5M22 9v6"/></svg>',
  work:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18m-11 0v2h4v-2"/></svg>',
  phone:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/></svg>',
  wifi:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9a14 14 0 0 1 18 0M6 12a9 9 0 0 1 12 0m-9 3a4 4 0 0 1 6 0"/><circle cx="12" cy="19" r="1"/></svg>',
  subscription:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 9h18m-5 4 1 1.5L19 13m-2 0v3"/></svg>',
  card:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/></svg>',
  tools:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 6 4-4 2 2-4 4M13 7 4 16l4 4 9-9M5 5l4 4"/></svg>',
  repair:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 5a5 5 0 0 0-6 6L3 16l5 5 5-5a5 5 0 0 0 6-6l-3 3-3-1-1-3z"/></svg>',
  beauty:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5zM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7z"/></svg>',
  flower:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="9" r="2"/><path d="M12 7C8 2 5 5 6 8c-4 1-2 5 1 5-2 4 2 5 5 1 3 4 7 3 5-1 3 0 5-4 1-5 1-3-2-6-6-1M12 14v7m0 0-3-3m3 3 3-3"/></svg>',
  camera:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h4l1-2h6l1 2h4v12H4z"/><circle cx="12" cy="13" r="3"/></svg>',
  bike:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="17" r="3"/><circle cx="18" cy="17" r="3"/><path d="M6 17l4-9h4l4 9M9 11h6M12 8l-1-3h3"/></svg>',
  fuel:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h9v18H5zM5 7h9m3-2 2 2v10a2 2 0 0 1-4 0v-5h-1"/><path d="M8 11h3"/></svg>',
  shirt:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 4 4 3 4-3 5 4-3 4-2-1v9H8v-9l-2 1-3-4 5-4Z"/></svg>',
  plane:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 3-7.5 18-3.8-7.7L2 9.5 21 3Z"/><path d="m9.7 13.3 4-4"/></svg>',
  train:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="3" width="12" height="15" rx="3"/><path d="M6 10h12M9 21l2-3m4 3-2-3M9 7h.01m6 0h.01"/></svg>',
  umbrella:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12a9 9 0 0 1 18 0c-2-1-4 1-6 0-2-1-4 1-6 0-2-1-4 1-6 0ZM12 12v6a3 3 0 0 0 5 2"/></svg>',
  dots:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>'
}[name] || '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7"/></svg>');
const navIcon = (name) => ({
  home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1V10Z"/></svg>',
  history:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5zM8 8h8m-8 4h8m-8 4h5"/></svg>',
  analytics:'<svg viewBox="0 0 24 24"><path d="M4 19V9m5 10V5m5 14v-7m5 7V8"/></svg>',
  categories:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><circle cx="12" cy="12" r="6"/><path d="M12 2.5v2M12 19.5v2M21.5 12h-2M4.5 12h-2M18.7 5.3l-1.4 1.4M6.7 17.3l-1.4 1.4M18.7 18.7l-1.4-1.4M6.7 6.7 5.3 5.3"/></svg>'
}[name]);
const DB = 'expenses-pwa'; let db;
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const d=request.result;if(!d.objectStoreNames.contains('categories'))d.createObjectStore('categories',{keyPath:'id'});if(!d.objectStoreNames.contains('expenses'))d.createObjectStore('expenses',{keyPath:'id'});if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'});};request.onsuccess=()=>{db=request.result;resolve()};request.onerror=()=>reject(request.error)});}
function store(name, mode='readonly'){return db.transaction(name,mode).objectStore(name)}
const all = (name) => new Promise((resolve,reject)=>{const r=store(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const get = (name,key) => new Promise((resolve,reject)=>{const r=store(name).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const put = (name,value) => new Promise((resolve,reject)=>{const r=store(name,'readwrite').put(value);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)});
const remove = (name,key) => new Promise((resolve,reject)=>{const r=store(name,'readwrite').delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)});
const state={categories:[],expenses:[],route:'home',sheet:null,dialog:null,archiveMonth:null,archiveLimit:20,analyticsMonth:monthKey(today()),analyticsYear:new Date().getFullYear()};
async function load(){state.categories=await all('categories');state.expenses=await all('expenses');state.categories.sort((a,b)=>a.isDefault===b.isDefault? a.name.localeCompare(b.name,'ru'):a.isDefault?-1:1)}
function category(id){return state.categories.find((x)=>x.id===id) || {name:'Категория',icon:'dots'}}
function byLatest(a,b){return b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt)}
function expensesFor(key){return state.expenses.filter((x)=>monthKey(x.date)===key)}
function totals(items){const sum=items.reduce((n,x)=>n+x.amountRubles,0), critical=items.filter((x)=>x.isCritical).reduce((n,x)=>n+x.amountRubles,0);return {sum,critical,noncritical:sum-critical,criticalPercent:sum?Math.round(critical/sum*100):0}}
function groups(items){const map=new Map();items.forEach((x)=>map.set(x.categoryId,(map.get(x.categoryId)||0)+x.amountRubles));return [...map.entries()].map(([id,amount])=>({category:category(id),amount})).sort((a,b)=>b.amount-a.amount)}
function route(){return location.hash.replace('#/','') || 'home'}
function nav(){const items=[['home','Главная'],['history','История'],['analytics','Аналитика'],['categories','Категории']];return `<nav class="bottom-nav" aria-label="Основная навигация">${items.map(([id,label])=>`<button class="nav-item ${state.route===id?'active':''}" data-route="${id}" aria-current="${state.route===id?'page':'false'}"><span class="nav-icon" aria-hidden="true">${navIcon(id)}</span><span>${label}</span></button>`).join('')}</nav>`}
function transaction(item){const c=category(item.categoryId);return `<button class="transaction" data-action="edit-expense" data-id="${item.id}" aria-label="Редактировать расход: ${esc(c.name)}, ${money(item.amountRubles)}"><span class="category-icon">${icon(c.icon)}</span><span class="transaction-main"><span class="transaction-name">${esc(c.name)}</span><br><span class="muted">${dateText(item.date)}</span>${item.isCritical?'<br><span class="tag">Критичный</span>':''}</span><span class="transaction-amount">${money(item.amountRubles)}</span></button>`}
function distribution(items){const data=groups(items).slice(0,3);if(!data.length)return '';const colors=['var(--primary)','var(--lilac)','var(--peach)'];let at=0;const stops=data.map((x,i)=>{const next=at+x.amount/totals(items).sum*100;const s=`${colors[i]} ${at}% ${next}%`;at=next;return s}).join(',');return `<div class="chart"><div class="donut" style="background:conic-gradient(${stops})" aria-label="Распределение расходов по категориям"></div><div class="legend">${data.map((x,i)=>`<div class="legend-row"><i class="dot" style="background:${colors[i]}"></i><span>${esc(x.category.name)}</span><b>${money(x.amount)}</b></div>`).join('')}</div></div>`}
function home(){const items=expensesFor(monthKey(today())),t=totals(items), top=groups(items).slice(0,3), latest=[...state.expenses].sort(byLatest).slice(0,5);if(!state.expenses.length)return `<header class="screen-head"><h1>Расходы</h1><button class="month-btn">${monthText(monthKey(today()))}</button></header><section class="card empty"><h2>Расходов пока нет</h2><p>Добавьте первую трату — так начнётся картина вашего месяца.</p><button class="primary wide" data-action="add-expense">Добавить расход</button></section>${nav()}`;return `<header class="screen-head"><h1>Расходы</h1><button class="month-btn">${monthText(monthKey(today()))}</button></header><section class="card soft summary"><div><div class="eyebrow">За текущий месяц</div><div class="amount">${money(t.sum)}</div></div><div class="round-icon" aria-hidden="true">▥</div></section><section class="card"><h2 class="section-title" style="margin-top:0"><span>По категориям</span></h2>${distribution(items)}</section><section class="card"><div class="section-title" style="margin-top:0"><h2>Топ категорий</h2></div>${top.length?top.map((x,i)=>`<div class="legend-row"><i class="dot" style="background:${['var(--primary)','var(--lilac)','var(--peach)'][i]}"></i><span>${esc(x.category.name)}</span><b>${money(x.amount)} · ${Math.round(x.amount/t.sum*100)}%</b></div>`).join(''):'<p class="muted">В этом месяце операций нет.</p>'}</section><section class="card peach metric-row"><div><div class="muted">Критичные расходы</div><strong>${money(t.critical)} · ${t.criticalPercent}%</strong></div><span class="round-icon" aria-hidden="true">!</span></section><div class="section-title"><h2>Последние операции</h2><button class="link" data-route="history">Все</button></div><section class="card">${latest.map(transaction).join('')}</section><button class="primary fixed-action" data-action="add-expense">Добавить расход</button>${nav()}`}
function history(){const items=[...state.expenses].sort(byLatest).slice(0,20);return `<header class="screen-head"><h1>История</h1></header><p class="muted">20 последних расходов</p>${items.length?`<section class="card">${items.map(transaction).join('')}</section>`:'<section class="card empty"><h2>История пуста</h2><p>Добавьте расход, чтобы он появился здесь.</p></section>'}<button class="secondary wide" data-route="archive">Открыть архив</button>${nav()}`}
function archive(){const months=[...new Set(state.expenses.map((x)=>monthKey(x.date)))].sort().reverse();if(!months.length)return `<header class="screen-head"><button class="icon-btn" data-route="history" aria-label="Назад">‹</button><h1>Архив</h1><span></span></header><section class="card empty"><h2>Архив пуст</h2><p>Старые расходы появятся здесь.</p></section>`;state.archiveMonth=months.includes(state.archiveMonth)?state.archiveMonth:months[0];const pos=months.indexOf(state.archiveMonth), items=expensesFor(state.archiveMonth).sort(byLatest).slice(0,state.archiveLimit);return `<header class="screen-head"><button class="icon-btn" data-route="history" aria-label="Назад">‹</button><h1>Архив</h1><span></span></header><section class="card"><div class="months"><button class="icon-btn" data-action="archive-prev" ${pos===months.length-1?'disabled':''} aria-label="Предыдущий месяц">‹</button><button class="month-btn" data-action="choose-archive-month">${monthText(state.archiveMonth)}</button><button class="icon-btn" data-action="archive-next" ${pos===0?'disabled':''} aria-label="Следующий месяц">›</button></div>${items.map(transaction).join('')}</section>${items.length<expensesFor(state.archiveMonth).length?'<button class="secondary wide" data-action="archive-more">Показать ещё</button>':''}`}
function analytics(){const key=state.analyticsMonth,items=expensesFor(key),t=totals(items), prev=new Date(`${key}-01T12:00:00`);prev.setMonth(prev.getMonth()-1);const prevItems=expensesFor(prev.toISOString().slice(0,7)),p=totals(prevItems),change=t.sum-p.sum;const values=Array.from({length:12},(_,i)=>totals(expensesFor(`${state.analyticsYear}-${String(i+1).padStart(2,'0')}`)).sum),max=Math.max(...values,1);return `<header class="screen-head"><h1>Аналитика</h1><button class="month-btn" data-action="choose-analytics-month">${monthText(key)}</button></header><section class="card soft"><div class="muted">Расходы за месяц</div><div class="amount">${money(t.sum)}</div><p class="muted">${p.sum?`${change>=0?'На':'На'} ${money(Math.abs(change))} ${change>=0?'больше':'меньше'}, чем в ${monthText(prev.toISOString().slice(0,7)).toLowerCase()} (${Math.round(change/p.sum*100)}%)`:'Нет данных для сравнения с прошлым месяцем'}</p></section><section class="card"><h2 class="section-title" style="margin-top:0"><span>По категориям</span></h2>${items.length?distribution(items):'<p class="muted">За этот месяц расходов нет.</p>'}</section><section class="card lilac"><div class="muted">Критичные расходы</div><div class="amount" style="font-size:25px">${money(t.critical)}</div><span>${t.criticalPercent}% от всех расходов</span><hr style="border:0;border-top:1px solid #ffffff90;margin:14px 0"><div class="muted">Некритичные: ${money(t.noncritical)} · ${t.sum?100-t.criticalPercent:0}%</div></section><section class="card"><div class="screen-head" style="margin-bottom:0"><h2>Динамика за год</h2><button class="month-btn" data-action="change-year">${state.analyticsYear}</button></div><div class="year-bars">${values.map((v,i)=>`<div class="year-bar" style="height:${v/max*118}px" tabindex="0" aria-label="${i+1} месяц: ${money(v)}"><span class="year-value" aria-hidden="true">${chartMoney(v)}</span><span class="year-month">${['Я','Ф','М','А','М','И','И','А','С','О','Н','Д'][i]}</span></div>`).join('')}</div></section>${nav()}`}
function categories(){const defaults=state.categories.filter((x)=>x.isDefault),custom=state.categories.filter((x)=>!x.isDefault);const list=(items,editable)=>`<section class="card">${items.map((c)=>`<div class="transaction"><span class="category-icon">${icon(c.icon)}</span><span class="transaction-main"><span class="transaction-name">${esc(c.name)}</span></span>${editable?`<button class="edit-link" data-action="edit-category" data-id="${c.id}">Переименовать</button>`:''}</div>`).join('')}</section>`;return `<header class="screen-head"><h1>Категории</h1><button class="month-btn" data-action="add-category">+ Добавить</button></header><div class="category-section-title">Стандартные</div>${list(defaults,false)}<div class="category-section-title">Мои категории</div>${custom.length?list(custom,true):'<p class="muted">Пользовательских категорий пока нет.</p>'}<p class="muted">Стандартные категории нельзя изменить. Свои можно переименовывать.</p>${nav()}`}
function calendar(value){const d=new Date(`${value}-01T12:00:00`),year=d.getFullYear(),month=d.getMonth(),first=(d.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),t=today();return `<div class="calendar">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((x)=>`<span class="weekday">${x}</span>`).join('')}${Array.from({length:first},()=>'<span></span>').join('')}${Array.from({length:days},(_,i)=>{const iso=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`,future=iso>t;return `<button class="day ${iso===value?'selected':''} ${future?'future':''}" data-action="pick-date" data-date="${iso}" ${future?'disabled':''}>${i+1}</button>`}).join('')}</div>`}
function expenseSheet(id){const x=state.sheet?.draft || (id?state.expenses.find((e)=>e.id===id):{amountRubles:'',categoryId:state.categories[0]?.id||'',date:today(),isCritical:false});return `<div class="sheet-backdrop"><form class="sheet" id="expense-form"><div class="sheet-title"><h2>${id?'Редактировать расход':'Добавить расход'}</h2><button type="button" class="icon-btn" data-action="close-sheet" aria-label="Закрыть">×</button></div><input type="hidden" name="id" value="${id||''}"><label class="field-label" for="amount">Сумма</label><div class="field-suffix"><input class="field amount-field" id="amount" name="amount" inputmode="numeric" autocomplete="off" value="${x.amountRubles}" required><span>₽</span></div><p class="error" data-error="amount"></p><label class="field-label">Категория</label><button type="button" class="field select-btn" data-action="choose-category" data-selected="${x.categoryId}"><span>${esc(category(x.categoryId).name)}</span><span>⌄</span></button><input type="hidden" name="categoryId" value="${x.categoryId}"><p class="error" data-error="categoryId"></p><label class="field-label">Дата</label><input class="field" type="hidden" name="date" value="${x.date}"><div id="calendar">${calendar(x.date)}</div><p class="error" data-error="date"></p><label class="switch-row"><span><b>Критичный расход</b><p>Отметьте обязательную трату</p></span><input class="switch" type="checkbox" name="isCritical" ${x.isCritical?'checked':''}></label><button class="primary wide" type="submit">${id?'Сохранить изменения':'Сохранить'}</button>${id?'<button type="button" class="danger wide" style="margin-top:12px" data-action="ask-delete" data-id="'+id+'">Удалить расход</button>':''}</form></div>`}
function categorySheet(id){const c=id?category(id):{name:'',icon:'bag'},icons=['bag','car','bus','home','health','cross','dumbbell','book','cup','cutlery','gift','film','music','game','pet','baby','education','work','phone','wifi','subscription','card','tools','repair','beauty','flower','camera','bike','fuel','shirt','plane','train','umbrella','dots'];return `<div class="sheet-backdrop"><form class="sheet" id="category-form"><div class="sheet-title"><h2>${id?'Переименовать категорию':'Новая категория'}</h2><button type="button" class="icon-btn" data-action="close-sheet" aria-label="Закрыть">×</button></div><input type="hidden" name="id" value="${id||''}"><label class="field-label" for="category-name">Название</label><input class="field" id="category-name" name="name" value="${esc(c.name)}" required maxlength="40"><p class="error" data-error="name"></p>${id?'':`<div class="field-label">Иконка</div><div class="icon-picker" role="group" aria-label="Выбор иконки">${icons.map((i)=>`<button type="button" class="icon-choice ${i===c.icon?'selected':''}" data-action="pick-icon" data-icon="${i}" aria-label="${iconLabel[i]}" aria-pressed="${i===c.icon}">${icon(i)}</button>`).join('')}</div><input type="hidden" name="icon" value="${c.icon}">`}<button class="primary wide" style="margin-top:22px" type="submit">Сохранить</button></form></div>`}
function chooser(type,selected){const entries=type==='category'?state.categories.map((c)=>`<button class="choice ${c.id===selected?'selected':''}" data-action="select-category" data-id="${c.id}"><span class="category-icon">${icon(c.icon)}</span>${esc(c.name)}</button>`):[...new Set(state.expenses.map((x)=>monthKey(x.date)))].sort().reverse().map((m)=>`<button class="choice ${m===selected?'selected':''}" data-action="select-month" data-type="${type}" data-month="${m}">${monthText(m)}</button>`);return `<div class="sheet-backdrop"><section class="sheet"><div class="sheet-title"><h2>${type==='category'?'Выберите категорию':'Выберите месяц'}</h2><button class="icon-btn" data-action="close-sheet" aria-label="Закрыть">×</button></div>${entries.join('')||'<p class="muted">Нет доступных месяцев.</p>'}</section></div>`}
function overlays(){if(state.dialog)return `<div class="sheet-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Удалить расход?</h2><p>Это действие нельзя отменить.</p><div class="dialog-actions"><button class="secondary" data-action="close-dialog">Отмена</button><button class="danger" data-action="confirm-delete" data-id="${state.dialog}">Удалить расход</button></div></section></div>`;if(!state.sheet)return '';if(state.sheet.type==='expense')return expenseSheet(state.sheet.id);if(state.sheet.type==='category')return categorySheet(state.sheet.id);return chooser(state.sheet.type==='category-choose'?'category':state.sheet.type,state.sheet.selected)}
function render(){state.route=route();const view={home,history,archive,analytics,categories}[state.route]||home;app.innerHTML=view()+overlays();const expenseForm=$('#expense-form'),categoryForm=$('#category-form');if(expenseForm)expenseForm.onsubmit=(event)=>{event.preventDefault();saveExpense(expenseForm)};if(categoryForm)categoryForm.onsubmit=(event)=>{event.preventDefault();saveCategory(categoryForm)};}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('visible'),2600)}
async function seed(){if(!(await get('settings','seeded'))){for(const [name,ic] of defaultCategories)await put('categories',{id:uid(),name,icon:ic,isDefault:true,createdAt:new Date().toISOString()});await put('settings',{key:'seeded',value:true});}}
function formError(form,name,msg){$(`[data-error="${name}"]`,form).textContent=msg}
async function saveExpense(form){const data=new FormData(form),amount=String(data.get('amount')).trim(),date=data.get('date'),categoryId=data.get('categoryId');['amount','date','categoryId'].forEach((x)=>formError(form,x,''));let valid=true;if(!/^\d+$/.test(amount)||Number(amount)<1){formError(form,'amount','Введите положительную сумму в целых рублях.');valid=false}if(!categoryId){formError(form,'categoryId','Выберите категорию.');valid=false}if(!date||date>today()){formError(form,'date','Выберите дату не позднее сегодняшней.');valid=false}if(!valid)return;const now=new Date().toISOString(),old=data.get('id')?state.expenses.find((x)=>x.id===data.get('id')):null;await put('expenses',{id:old?.id||uid(),amountRubles:Number(amount),categoryId,date,isCritical:data.get('isCritical')==='on',createdAt:old?.createdAt||now,updatedAt:now});await load();state.sheet=null;location.hash='#/history';toast(old?'Расход изменён':'Расход добавлен')}
async function saveCategory(form){const data=new FormData(form),name=String(data.get('name')).trim(),id=data.get('id');formError(form,'name','');if(!name){formError(form,'name','Введите название категории.');return}if(state.categories.some((c)=>c.id!==id&&c.name.localeCompare(name,'ru',{sensitivity:'base'})===0)){formError(form,'name','Категория с таким названием уже есть.');return}const old=id?category(id):null;await put('categories',{id:old?.id||uid(),name,icon:old?.icon||data.get('icon'),isDefault:false,createdAt:old?.createdAt||new Date().toISOString()});await load();state.sheet=null;render();toast(old?'Категория переименована':'Категория создана')}
document.addEventListener('submit',(e)=>{if(e.target.id==='expense-form'){e.preventDefault();saveExpense(e.target)}if(e.target.id==='category-form'){e.preventDefault();saveCategory(e.target)}});
document.addEventListener('click',async(e)=>{const b=e.target.closest('[data-action],[data-route]');if(!b)return;if(b.dataset.route){location.hash='#/'+b.dataset.route;return}const a=b.dataset.action;if(a==='add-expense'){state.sheet={type:'expense'};render()}if(a==='edit-expense'){state.sheet={type:'expense',id:b.dataset.id};render()}if(a==='close-sheet'){state.sheet=null;render()}if(a==='choose-category'){const form=$('#expense-form');state.sheet={type:'category-choose',selected:b.dataset.selected,draft:{amountRubles:form.amount.value,categoryId:b.dataset.selected,date:form.date.value,isCritical:form.isCritical.checked,id:form.id.value}};render()}if(a==='select-category'){const draft=state.sheet.draft;draft.categoryId=b.dataset.id;state.sheet={type:'expense',id:draft.id||undefined,draft};render()}if(a==='pick-date'){const form=$('#expense-form');form.date.value=b.dataset.date;$('#calendar').innerHTML=calendar(b.dataset.date)}if(a==='ask-delete'){state.dialog=b.dataset.id;render()}if(a==='close-dialog'){state.dialog=null;render()}if(a==='confirm-delete'){await remove('expenses',b.dataset.id);await load();state.dialog=null;state.sheet=null;location.hash='#/history';render();toast('Расход удалён')}if(a==='add-category'){state.sheet={type:'category'};render()}if(a==='edit-category'){state.sheet={type:'category',id:b.dataset.id};render()}if(a==='pick-icon'){const form=$('#category-form');form.icon.value=b.dataset.icon;form.querySelectorAll('[data-action="pick-icon"]').forEach((x)=>{const selected=x===b;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',String(selected))})}if(a==='choose-archive-month'){state.sheet={type:'archive',selected:state.archiveMonth};render()}if(a==='choose-analytics-month'){state.sheet={type:'analytics',selected:state.analyticsMonth};render()}if(a==='select-month'){if(b.dataset.type==='archive')state.archiveMonth=b.dataset.month;else state.analyticsMonth=b.dataset.month;state.sheet=null;render()}if(a==='archive-more'){state.archiveLimit+=20;render()}if(a==='archive-prev'||a==='archive-next'){const months=[...new Set(state.expenses.map((x)=>monthKey(x.date)))].sort().reverse(),pos=months.indexOf(state.archiveMonth);state.archiveMonth=months[pos+(a==='archive-prev'?1:-1)];state.archiveLimit=20;render()}if(a==='change-year'){state.analyticsYear=state.analyticsYear===new Date().getFullYear()?state.analyticsYear-1:state.analyticsYear+1;render()}});
window.addEventListener('hashchange',render);
async function start(){await openDb();await seed();await load();const seen=await get('settings','onboardingSeen');if(!seen&&!location.hash){app.innerHTML=`<section class="onboarding"><div class="onboarding-mark">₽</div><h1>Расходы —<br>под контролем</h1><p>Быстро записывайте траты, указывайте фактическую дату и смотрите картину месяца.</p><div class="steps"><i class="active"></i><i></i><i></i></div><button class="primary wide" id="start">Начать</button></section>`;$('#start').onclick=async()=>{await put('settings',{key:'onboardingSeen',value:true});location.hash='#/home';render()};return}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}
start();
